from workflows import EXPECTED_WORKFLOWS

INDUSTRY_SECTORS = [
    '1: Live animals and animal products',
    '2: Vegetable products',
    '3: Animal and vegetable fats, oils and waxes',
    '4: Prepared foods, drinks, tobacco',
    '5: Mineral products',
    '6: Chemical products',
    '7: Plastics and rubber',
    '8: Animal skins, saddlery, travel cases, bags',
    '9: Wood, cork, basketware',
    '10: Paper and paperboard',
    '11: Textiles',
    '12: Footwear, headgear, feathers, artificial flowers',
    '13: Stone, ceramic, glass items',
    '14: Pearls, (semi-)precious stones, jewellery, coins',
    '15: Base metals',
    '16: Machinery, mechanical and electrical equipment',
    '17: Vehicles, aircraft, vessels, transport equipment',
    '18: Instruments incl. optical, measuring, medical, clocks',
    '19: Arms and ammunition',
    '20: Miscellaneous manufactured items',
    '21: Works of art, antiques'
]

COUNTRIES = [
    'Afghanistan',
    'Åland Islands',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bonaire, Sint Eustatius and Saba',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Indian Ocean Territory',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos (Keeling) Islands',
    'Colombia',
    'Comoros',
    'Congo',
    'Congo (the Democratic Republic of the)',
    'Cook Islands',
    'Costa Rica',
    "Côte d'Ivoire",
    'Croatia',
    'Cuba',
    'Curaçao',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Falkland Islands [Malvinas]',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard Island and McDonald Islands',
    'Holy See',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    "Laos",
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macao',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia (Federated States of)',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'North Korea',
    'Northern Mariana Islands',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine, State of',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Pitcairn',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Réunion',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Barthélemy',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin (French part)',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and the South Sandwich Islands',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Svalbard and Jan Mayen',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States Minor Outlying Islands',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Virgin Islands (British)',
    'Virgin Islands (U.S.)',
    'Wallis and Futuna',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe'
]

CASE_TYPES = EXPECTED_WORKFLOWS.keys()
CUSTOMER_CREATEABLE_CASE_TYPES = [
    'Anti-dumping investigation',
    'Anti-subsidy investigation'
]
CASE_TYPE_PREFIXES = {
    'Transition anti-dumping review': 'TD',
    'Transition anti-subsidy review': 'TS',
    'Transition safeguarding review': 'TF',
    'Anti-dumping investigation': 'AD',
    'Anti-subsidy investigation': 'AS',
    'Interim review': 'IR',
    'Scope review': 'SC',
    'Expiry review': 'ER',
    'Absorption review': 'AR',
    'Circumvention review': 'CR',
    'New exporter review': 'NE',
    'Undertaking review': 'UR',
    'Suspension review': 'SR',
    'Refund request': 'RR',
    'Dispute ruling': 'DR',
    'Safeguarding': 'SF',
    'Safeguard mid-term review': 'SM',
    'Safeguard extension review': 'SE',
    'Safeguard suspension review': 'SS',
    'Safeguard discontinuation': 'SD',
    'Breach of undertakings': 'BU'
}

PUBLIC_NOTICE_TYPES = [
    "Notice of Initiation",
    "Final determination",
    "The Statement of Essential Facts",
    "General publication",
    "Provisional determination",
    "Statement of intended final determination",
    "Reconsideration report"
]

DASHBOARD_EXPECTED_LINKS = [
        #'0300 222 0000',
        'help@traderemedies.gov.uk',
        #'Online help on TRA website',
        'Register interest in a case'
    ]


WTO_MIN_QUESTIONNAIRE_RESPONSE_DAYS = 37
